
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dof-exam-2021-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: dof-exam-2021
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: dof-exam-2021
    spec:
      containers:
      - name: app-cont
        image: hotval/dof-exam-2021:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: dof-exam-2021-svc
  labels:
    app: dof-exam-2021
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32000
    protocol: TCP
  selector:
    app: dof-exam-2021
